version: '2'
services:
    tx-app:
        image: tx
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tx-postgresql:5432/tx
            - JHIPSTER_CACHE_MEMCACHED_SERVERS=tx-memcached:11211
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
    tx-postgresql:
        extends:
            file: postgresql.yml
            service: tx-postgresql
    tx-memcached:
        extends:
            file: memcached.yml
            service: tx-memcached
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
